#!/bin/sh
#
# forgit = for each git repository do <command> given in $*
# by Håkan Isaksson, INIT AB
#
test -z "$1" && {
    echo "Short description:"
    echo "forgit = for each git repository found do <command> given in $*"
    echo "Description:"
    echo "   Searches recursively for git repositories (ie any dir with a .git directory) "
    echo "   and cd to that directory and run the command and arguments given to this script"
    echo "usage:"
    echo "   forgit <command>"
    echo "examples:"
    echo "   forgit gitup" 
    echo "   forgit gitup -u" 
    echo "   forgit git status -s"
    exit 2
}

REPOS=`find . -type d -name '.git' | awk -F\/ '{ for (i=1; i<NF; i++) printf "%s/",$i; printf "\n"; }'`

test -z "$REPOS" && {
    echo "No git repos found."
    exit 1
}

for R in $REPOS; do
    echo for $R: $*
    (cd $R && $* )
done